{% set name = "asdf-standard" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_standard-{{ version }}.tar.gz
  sha256: afd8ff9a70e7b17f6bcc64eb92a544867d5d4fe1f0076719142fdf62b96cfd44

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - importlib_resources >=3
    - python >=3.8

test:
  imports:
    - asdf_standard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asdf-format/asdf-standard
  summary: The ASDF Standard schemas
  license_family: BSD
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  anaconda-services:
    ref: https://anaconda.zendesk.com/agent/tickets/42309
    reason: Carl Zeiss ask
  recipe-maintainers:
    - ianaobi
    - bradley
    - jhunkeler
    - WilliamJamieson
    - braingram
