{% set name = "asdf-standard" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asdf_standard-{{ version }}.tar.gz
  sha256: 21cfc05dd821559b67dfbc54d03b2bcc0ad8b6cb5cc9d14d7591f73ab3451700

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
    - setuptools-scm
  run:
    - importlib-resources >=3
    - python >=3.8

test:
  imports:
    - asdf_standard
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/asdf-format/asdf-standard
  summary: The ASDF Standard schemas
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jhunkeler
    - WilliamJamieson
